### PR TITLE
Update index.html by arnab

### PR DESCRIPTION
**Pull request by arnab-datta**
Updated cs Go

### CODE REVIEW

**Comment by arnab-datta** [comment]
@ritwickdey check it.

**Comment by arnab-datta** [comment]
told u to check is it right or wrong?

**Comment by arnab-datta** [comment]
ami class name change korechi tai. ritwick thik kore di66e.

**Comment by ritwickdey** [comment]
Ami ki korlam 😕 ... event-5 class remove kore btn er class add korli keno

**Comment by prithweedas** [comment]
arrey oi 5th modal ta to puru chulke jabe -_-

**Comment by prithweedas** [comment]
oi div ta to puro tar wrapper chilo

**Comment by ritwickdey** [comment]
Eke bolar theke ami nije kore nebo ei bar theke.. ami bollam puro contain ta likhte.. just link add kore chere dilo... 😡😡😡😡

**Comment by ritwickdey** [comment]
Dekh ki korechis.. be nije to age try korbi

image

**Pull request merged**
